name: Deploy backend and frontend to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy ASP.NET Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish app
        run: dotnet publish -c Release -o out
        working-directory: ./PokeApiFly.API

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --config fly.toml --remote-only
        working-directory: ./PokeApiFly.API
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    name: Deploy Quasar Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: npm install
        working-directory: ./PokeApiFly.Web

      - name: Install Quasar CLI globally
        run: npm install -g @quasar/cli

      - name: Build Quasar app
        run: quasar build
        working-directory: ./PokeApiFly.Web

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --config fly.toml --remote-only
        working-directory: ./PokeApiFly.Web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
